export const PRODUCTS_IS_LOADING = 'PRODUCTS_IS_LOADING';
export const PRODUCTS_LOADING_ERROR = 'PRODUCTS_LOADING_ERROR';
export const PRODUCTS_LOADING_SUCCESS = 'PRODUCTS_LOADING_SUCCESS';
export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
export const SUBTRACT_PRODUCT = 'SUBTRACT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
