export const ADD_PRODUCT = 'ADD_PRODUCT';
export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
export const SUBTRACT_PRODUCT = 'SUBTRACT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
